spring:
  application:
    name: gratitude

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?currentScheme=${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${APP_SHOW_SQL:false}
    properties:
      hibernate:
      format_sql: ${APP_FORMAT_SQL:false}


  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    user: ${DB_USER}
    default-schema: ${DB_NAME}
    password: ${DB_PASSWORD}

token:
  security:
    jwt: ${JWT_SECRET}
